title: Tony's docs
description: None right now.
theme: just-the-docs

url: https://tonyzdev.github.io/mydocs

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
